name: Automatically index every Sunday

on:
  workflow_dispatch:
  schedule:
    # Run every Sunday at 00:20 UTC
    - cron: "20 0 * * 0"

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Specify your Python version
      - run: pip install -r requirements.txt

      # Run your Python script
      - name: Run the script
        run: |
          python index.py
