name: Automatically index every Sunday

on:
  workflow_dispatch:
  schedule:
    # Run every Sunday at 00:20 UTC
    - cron: "20 0 * * 0"

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Specify your Python version
      - run: pip install -r requirements.txt

      # Run your Python script
      - name: Run the script
        run: |
          python index.py

      # Configure git
      - name: Set up git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Add changes to git
      - name: Commit changes
        run: |
          git add .
          git commit -m "Automated Index commit from GitHub Actions"

      # Push changes back to the repository
      - name: Push changes
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
